spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dario2018/springcloud201812
          username: ---------
          password: *********
          search-paths: /*/*/*,/*
  rabbitmq:
    addresses: 192.168.206.128
    port: 5672
    username: guest
    password: guest
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-methods: "*"
        allowed-origins: "*"
