spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dario2018/springcloud201812
          username: Dario2018
          password: chen2014234123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/