spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dario2018/springcloud201812
          username: Dario2018
          password: chen2014234123
          search-paths: /*/*/*,/*
  rabbitmq:
    addresses: 192.168.206.128
    port: 5672
    username: guest
    password: guest
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"