eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false
  instance:
    hostname: https://www.cnblogs.com/xmf3628/p/11999956.html
spring:
  application:
    name: eureka
server:
  port: 8761