spring:
  application:
    name: goods
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: chen2018
  jpa:
    show-sql: true
  rabbitmq:
    addresses: 192.168.187.128
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        myMessage:
          group: order
          content-type: application/json
eureka:
  client:
    service-url:
#      defaultZone: http://192.168.187.128:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
#      链路监控：服务追踪
logging:
  level:
    org.springframework.cloud.openfeign: debug
