spring:
  application:
    name: schedule
#    datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: chen2018
#    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=UTF-8
#  jpa:
#    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/